#!/bin/bash
LOG_FILE=/tmp/dwm.$(date +%Y-%m-%d).log

echo "$(date +%Y%m%d-%H%M%S-%N) Sourcing bashrc to indirectly trigger .xsession ..." >> $LOG_FILE
source $HOME/.bashrc

DWM_BIN=$HOME/local/bin/dwm
echo "$(date +%Y%m%d-%H%M%S-%N) Starting dwm ($DWM_BIN) ..." >> $LOG_FILE
$DWM_BIN >> $LOG_FILE 2>&1


