#!/bin/bash
LOG_FILE=/tmp/dwm.$(date +%Y-%m-%d).log

DWM_BIN=$HOME/local/bin/dwm
echo "Starting dwm ($DWM_BIN) ..." >> $LOG_FILE
$DWM_BIN >> $LOG_FILE 2>&1

# ---
# Autostart Programs
# ---

# TODO: turn picom below on a shellscript that toggles compositing on and off.
picom --config ~/picom.conf --backend glx &

/usr/bin/lxpolkit &

/home/pi/apps/scripts/bin/clippy.py &

# TODO: setup and install trayer-ng, so that I can use the same network manager applet as lxde

# TODO: if there is a way to hide all windows and show the desktop, use conky do display some information on the desktop:
# notify-send 'Launching conky...' --urgency low; ~/.Conky/startconky.sh &

# TODO: maybe use polybar as a bottom bar, since dwm does not provide one?
# $HOME/.config/polybar/launch.sh &

# TODO: run battery_wall script below as a systemd user timer:
# cd /home/pi/apps/scripts/bin/battery_wallpaper && ./battery_wall.py &

